/**
 * @fileoverview
 * This file contains the hex color codes of all categories.
 * @author Preet P. Vadaliya
 */

Blockly.CONTROLS_CATEGORY_HUE = 230;
Blockly.LOOPS_CATEGORY_HUE = 230;
Blockly.ARITHMETIC_OPERATORS_CATEGORY_HUE = 230;
Blockly.ASSIGNMENT_OPERATORS_CATEGORY_HUE = 230;
Blockly.COMPARISON_OPERATORS_CATEGORY_HUE = 230;
Blockly.LOGICAL_OPERATORS_CATEGORY_HUE = 230;
Blockly.TYPE_OPERATORS_CATEGORY_HUE = 230;
Blockly.BITWISE_OPERATORS_CATEGORY_HUE = 230;
Blockly.MATHS_CATEGORY_HUE = 230;
Blockly.STRINGS_CATEGORY_HUE = 230;
Blockly.SETS_CATEGORY_HUE = 230;
Blockly.ARRAYS_CATEGORY_HUE = 230;
Blockly.OBJECTS_CATEGORY_HUE = 230;
Blockly.VARIABLES_CATEGORY_HUE = 230;
Blockly.FUNCTIONS_CATEGORY_HUE = 230;
